import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Four sidebars, one per navbar entry. Each is generated from its own folder,
// so adding a page means adding a file with `sidebar_position` in its
// frontmatter - there is nothing to keep in step here.
const sidebars: SidebarsConfig = {
  hosted: [{ type: 'autogenerated', dirName: 'hosted' }],
  selfHost: [{ type: 'autogenerated', dirName: 'self-host' }],
  reference: [{ type: 'autogenerated', dirName: 'reference' }],
  support: [{ type: 'autogenerated', dirName: 'support' }],
};

export default sidebars;
